[package]
name = "lucas"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tiny_http = "0.8"

[[bin]] 
name = "lucas"
path = "server.rs"
